### ISSUE TITLE
Valid values for imported i64 globals

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/JS-BigInt-integration#17]
In the current version of this proposal, any JavaScript object can be imported as an i64 global as long as [ToBigInt64](https://tc39.es/proposal-bigint/#sec-to-big-int64) does not throw an exception on that object. However, in the main WebAssembly spec we require at the moment that only JavaScript numbers are valid values for imported globals. I think this behavior was introduced to the WebAssembly spec with the mutable-globals proposal. 
With this issue I wanted to flag this inconsistenc, so that we don't forget about it.

**Comment by littledan** [comment]
Good catch. I agree that we should be checking for the type being Number or BigInt, rather than calling ToWebAssemblyValue on everything.

It looks like the specification draft in this repository needs a rebase for a few things that changed in master. @Ms2ger are you available to do this? It would also be good to make sure we have test coverage for these points.

**Comment by rossberg** [comment]
Agreed that the type check should be more strict.

**Comment by Ms2ger** [comment]
Fwiw, the strict type check dates back to the initial checkin of the JSAPI spec. I'm not sure it makes a great deal of sense in JS, but any discussion about that should happen in the main repo anyway.
